version: '3.8'

services:
  devops-mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    volumes:
      # Mount app directory for development (hot reload)
      - ./app:/app/app
    restart: unless-stopped
    # Enable hot reload for development
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
